package WordNet;

public enum InterlingualDependencyType {
    HYPERNYM, NEAR_ANTONYM, HOLO_MEMBER, HOLO_PART, HOLO_PORTION,
    USAGE_DOMAIN, CATEGORY_DOMAIN, BE_IN_STATE, SUBEVENT, VERB_GROUP,
    SIMILAR_TO, ALSO_SEE, CAUSES, SYNONYM
}
